### ISSUE TITLE
ProConnect erreur 500

### ISSUE THREAD

**Issue by vincentporte** [gip-inclusion/itou-communaute-django#819]
```
2024-11-14T12:23:03.384Z ERROR 2024-11-14 13:23:03,381 /home/bas/venv/lib/python3.12/site-packages/django/utils/log.py : Internal Server Error: /pro_connect/callback
Traceback (most recent call last):
  File "/home/bas/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bas/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bas/venv/lib/python3.12/site-packages/sentry_sdk/integrations/django/views.py", line 90, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/host/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/bas/app_be9c4821-d5c0-4470-b290-d5d33ad9b4f9/lacommunaute/openid_connect/views.py", line 125, in pro_connect_callback
    user_data = jwt.decode(
                ^^^^^^^^^^^
  File "/home/bas/venv/lib/python3.12/site-packages/jwt/api_jwt.py", line 211, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bas/venv/lib/python3.12/site-packages/jwt/api_jwt.py", line 152, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bas/venv/lib/python3.12/site-packages/jwt/api_jws.py", line 210, in decode_complete
    self._verify_signature(signing_input, header, signature, key, algorithms)
  File "/home/bas/venv/lib/python3.12/site-packages/jwt/api_jws.py", line 304, in _verify_signature
    raise InvalidAlgorithmError("The specified alg value is not allowed")
jwt.exceptions.InvalidAlgorithmError: The specified alg value is not allowed
```

**Comment by vincentporte** [comment]
resolution : demander à proconnect d'utiliser l'algorithme `HS256` et non `RS256`
